### ISSUE TITLE
getDeviceLldpCdp Output

### ISSUE THREAD

**Issue by DakotaGeek** [PackeTsar/meraki-cli#15]
When using the command `meraki devices getDeviceLldpCdp --serial <serial num>`, the resulting table contains only the "sourceMac" and none of the actual LLDP or CDP data.  

Trying it with the -ddd argument, we recieve the following `Discarding data in table squash: ports: {'4': {'cdp'....`.  The code is obviously retrieving the CDP/LLDP results but discarding the wrong parts in order to create the table.

Thank you so much for creating this tool, it is excellent for quick lookups and adjustments!

**Comment by PackeTsar** [comment]
Use the `-j` switch (like `meraki -j`) to view JSON data. The table squash happens because the CDP/LLDP data cannot be tabulated since it is complex data.
