### ISSUE TITLE
Is there a way to update an AP's DHCP VLAN entry?  

### ISSUE THREAD

**Issue by gleep52** [PackeTsar/meraki-cli#20]
Let's say we have Access Points in different buildings and use different VLANs to pull DHCP.  Is there a CLI method to update the VLAN entry so it still uses DHCP, but the VLAN ID changes from 200 to 100 or something like that?  I saw issue 17 which was a request for extra features.  (https://github.com/PackeTsar/meraki-cli/issues/17).  Is there anything like that for DHCP VLAN ID's for devices?

**Comment by PackeTsar** [comment]
Are you looking to change the VLAN assigned to the switchports so the APs get DHCP IPs from a different network?

**Comment by gleep52** [comment]
No - nothing to do with switchports.  On the AP page in the dashboard there's the option to statically assign it an IP or leave it DHCP with a VLAN field.  I need to change that VLAN field for over 200 APs... CLI would be a godsend for that.

**Comment by PackeTsar** [comment]
Yea you can do it with `meraki -j devices updateDeviceManagementInterface --serial XXXX-XXXX-XXXX --wan1 '{"vlan": 2}'`

Kind of weird how Meraki's API exposes this control with the `wan1` key, but I just tested it on a switch and it seems to work.

https://github.com/PackeTsar/meraki-cli/blob/master/COMMAND_GUIDE.md#devices-update-device-management-interface

https://developer.cisco.com/meraki/api-v1/update-device-management-interface/

**Comment by PackeTsar** [comment]
Oh also, you have to use the JSON structure like `--wan1 '{"vlan": 2}'` because the API requires the `wan1` argument to be a complex object instead of a simple value.

**Comment by gleep52** [comment]
Yes - thank you - this works perfect for APs, as well as switches too!  Gosh I'm so happy right now haha

**Comment by PackeTsar** [comment]
No problem. It's a common use case. I added it to the cheatsheet

https://github.com/PackeTsar/meraki-cli/blob/master/CHEATSHEET.md#change-device-management-vlanipdns
